[phases.setup]
nixPkgs = ['php82', 'nodejs_18', 'npm', 'bash']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci',
    'npm run build'
]

[phases.build]
cmds = [
    'php artisan config:clear',
    'php artisan cache:clear',
    'php artisan route:clear',
    'php artisan view:clear',
    'chmod -R 755 storage',
    'chmod -R 755 bootstrap/cache'
]

[start]
cmd = 'bash start.sh' 